"use strict";

!function() {
    const t = new Map([ [ "investire.biz", 0 ], [ "mediamarkt.ch", 1 ], [ "mediaworld.it", 1 ], [ "adnkronos.com", 2 ], [ "cronacadiverona.com", 3 ], [ "lospiffero.com", 4 ], [ "agi.it", 5 ], [ "ilprogettistaindustriale.it", 6 ], [ "laleggepertutti.it", 7 ], [ "logisticanews.it", 8 ], [ "tgcom24.mediaset.it", 9 ], [ "paginegialle.it", 10 ], [ "pharmacyscanner.it", 11 ], [ "radioluna.it", 12 ], [ "technofashion.it", 13 ], [ "guadagna.net", 14 ], [ "tuttoandroid.net", 15 ] ]), s = new Map(void 0), a = new Map(void 0);
    self.proceduralImports = self.proceduralImports || [], self.proceduralImports.push({
        argsList: [ [ '{"selector":".container-fluid.py-3.bg-white-color.pl-5.pr-5","tasks":[["has",{"selector":".text-black.weight-400.mb-0","tasks":[["has-text","I Nostri Partners"]]}]]}' ], [ '{"selector":"li[data-index-number]","tasks":[["has",{"selector":"[data-test=\\"mms-product-card\\"]","tasks":[["has-text","Sponsorizzati"]]}]]}' ], [ '{"selector":".cont-ev-list","tasks":[["has",{"selector":".title-channel","tasks":[["has-text","in Evidenza"]]}]]}' ], [ '{"selector":".td_block_template_1","tasks":[["has",{"selector":".td-block-title-wrap","tasks":[["has-text","Banner"]]}]]}' ], [ '{"selector":".article-blog-default","tasks":[["has",{"selector":"span","tasks":[["has-text","CONTENUTO SPONSORIZZATO"]]}]]}' ], [ '{"selector":".agi-article-card","tasks":[["has",{"selector":".article-category","tasks":[["has-text","BRANDED CONTENT"]]}]]}' ], [ '{"selector":".td_block_wrap","tasks":[["has",{"selector":"span","tasks":[["has-text","Contenuti sponsorizzati"]]}]]}' ], [ '{"selector":".cl-amp-important-information","tasks":[["has",{"selector":"div","tasks":[["has-text","Annuncio pubblicitario"]]}]]}', '{"selector":".custom-html","tasks":[["has",{"selector":"div","tasks":[["has-text","Annuncio pubblicitario"]]}]]}' ], [ '{"selector":".td_block_wrap","tasks":[["has",{"selector":"a","tasks":[["has-text","Contenuti sponsorizzati"]]}]]}' ], [ '{"selector":".right.es.large","tasks":[["has",{"selector":"span","tasks":[["has-text","contenuto sponsorizzato"]]}]]}' ], [ '{"selector":".search-itm","tasks":[["has",{"selector":".search-itm__label","tasks":[["has-text","annuncio"]]}]]}' ], [ '{"selector":".similar-post-holder","tasks":[["has",{"selector":".categoria","tasks":[["has-text","Post sponsorizzato"]]}]]}' ], [ '{"selector":".feat-widget-wrap","tasks":[["has",{"selector":"div","tasks":[["has-text","INFORMAZIONE REDAZIONALE"]]}]]}' ], [ '{"selector":".td_block_wrap","tasks":[["has",{"selector":"span","tasks":[["has-text","Advertorial"]]}]]}' ], [ '{"selector":"center","tasks":[["has",{"selector":"a","tasks":[["has-text","Esponi i tuoi banner sul forum"]]}]]}' ], [ '{"selector":".card.dark","tasks":[["has",{"selector":"span","tasks":[["has-text","Adv"]]}]]}' ] ],
        hostnamesMap: t,
        entitiesMap: s,
        exceptionsMap: a
    });
}();